# Generated by Django 4.1.3 on 2022-12-03 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="createrd",
            new_name="created",
        ),
    ]
